import type { Metadata } from "next";
import Link from "next/link";
import {
  LegalList,
  LegalPage,
  LegalSection,
} from "@/app/(landing)/_components/legal-page";
import { PLATFORM_EMAILS, PRODUCT_NAME } from "@/config/platform";
import { pageOpenGraph, pageTwitter } from "@/lib/seo/metadata";

export const metadata: Metadata = {
  title: "Acceptable Use Policy",
  description: `What you can and cannot run on ${PRODUCT_NAME}.`,
  alternates: { canonical: "/aup" },
  openGraph: pageOpenGraph({
    url: "/aup",
    title: `Acceptable Use Policy — ${PRODUCT_NAME}`,
    description: `What you can and cannot run on ${PRODUCT_NAME}.`,
  }),
  twitter: pageTwitter({
    title: `Acceptable Use Policy — ${PRODUCT_NAME}`,
    description: `What you can and cannot run on ${PRODUCT_NAME}.`,
  }),
};

const LAST_UPDATED = "31 May 2026";

export default function AupPage() {
  return (
    <LegalPage
      intro={
        <p>
          This Acceptable Use Policy (the &ldquo;AUP&rdquo;) describes the
          activities that are not allowed on {PRODUCT_NAME}. It applies to
          everyone who uses the Service, including the people you grant access
          to your spaces. The AUP forms part of our{" "}
          <Link className="text-primary hover:underline" href="/terms">
            Terms of Service
          </Link>{" "}
          and breaching it is a material breach of those Terms. We may
          investigate and act on any suspected violation, with or without notice
          and in our sole discretion, including by suspending or terminating
          accounts and forfeiting unused credit and prepaid fees.
        </p>
      }
      lastUpdated={LAST_UPDATED}
      title="Acceptable Use Policy"
    >
      <LegalSection id="responsibility" title="1. Your responsibility">
        <p>
          You are responsible for everything that runs in your spaces and Cubes
          — including software you install yourself, code generated by others on
          your behalf, and any traffic generated by your end users. If your end
          users misuse the Service through your account, we treat that as your
          conduct under this AUP. You remain liable for activity carried out
          under your credentials even if you did not authorise it.
        </p>
      </LegalSection>

      <LegalSection id="prohibited-content" title="2. Prohibited content">
        <p>
          You must not use the Service to host, store, transmit, distribute or
          link to:
        </p>
        <LegalList>
          <li>
            child sexual abuse material (CSAM) or any content that sexually
            exploits a minor;
          </li>
          <li>
            content that promotes, incites, glorifies or facilitates terrorism,
            mass violence or other serious crime;
          </li>
          <li>
            content that incites hatred or violence against people on the basis
            of protected characteristics;
          </li>
          <li>
            non-consensual intimate imagery, deepfakes designed to harm, doxxing
            material or content designed to harass, threaten or stalk;
          </li>
          <li>
            malware, ransomware, exploit kits, phishing kits, spyware,
            stalkerware, credential-harvesting pages or other malicious tooling;
          </li>
          <li>
            content that infringes the intellectual-property rights of others
            (including pirated software, films, books, courses, games, music or
            other unauthorised distribution) or that facilitates such
            infringement;
          </li>
          <li>
            content that violates applicable privacy, export-control, sanctions,
            anti-money-laundering or other laws;
          </li>
          <li>
            unsolicited bulk or commercial messages, unlawful gambling,
            fraudulent goods and services, pyramid or Ponzi schemes, deceptive
            financial offerings, or content designed to deceive users into
            making payments.
          </li>
        </LegalList>
      </LegalSection>

      <LegalSection id="prohibited-activities" title="3. Prohibited activities">
        <p>You must not use the Service to:</p>
        <LegalList>
          <li>
            attack, probe, scan, fuzz, brute-force or intentionally degrade any
            system, network or service without explicit written authorisation
            from its owner — this includes denial-of-service and
            distributed-denial-of-service attacks, brute-force credential
            attacks, port scanning, vulnerability scanning, password spraying
            and amplification attacks;
          </li>
          <li>
            attempt to gain unauthorised access to any account, system or
            network — including other {PRODUCT_NAME} customers&apos; Cubes, our
            infrastructure, our payment provider or any third party — or to
            circumvent any technical or contractual access restriction;
          </li>
          <li>
            send unsolicited, deceptive or otherwise unlawful commercial
            messages (spam) by email, SMS, instant messaging, push notification
            or any other channel, including messages that violate CAN-SPAM,
            CASL, the EU ePrivacy Directive, the UK Privacy and Electronic
            Communications Regulations or any equivalent law;
          </li>
          <li>
            operate command-and-control infrastructure for botnets, malware,
            stalkerware, coordinated inauthentic behaviour or any other
            automated abuse network;
          </li>
          <li>
            evade or interfere with rate limits, quotas, plan limits, billing or
            fraud controls — including running multiple accounts to circumvent
            free credit, abusing trial offers, initiating chargebacks intended
            to keep services for free, or otherwise abusing the overage and
            credit systems;
          </li>
          <li>
            run cryptocurrency mining, hash-grinding, proof-of-work workloads,
            generic distributed-compute marketplaces (including paid
            background-CPU programs) or similar workloads whose primary purpose
            is monetising raw compute, except with our explicit prior written
            consent;
          </li>
          <li>
            run open proxies, open VPN exit nodes, Tor exit nodes or other
            services that anonymise third-party traffic without robust abuse
            controls and our prior written consent;
          </li>
          <li>
            run gambling, adult content, financial-services, healthcare,
            pharmaceutical or other high-risk workloads without holding and
            complying with all licences, approvals and registrations required
            where you and your users are located;
          </li>
          <li>
            host or operate services used in life-critical situations (medical
            diagnosis or decision-making, aviation, nuclear, weapons control,
            mass transit, emergency response, critical-safety infrastructure) —
            the Service is not designed, intended or approved for such use;
          </li>
          <li>
            disrupt, interfere with or impair the integrity, performance or
            stability of the Service, our infrastructure or the experience of
            other customers, including by sustained excessive resource
            consumption, abusive use of shared resources or behaviour that we,
            in our sole discretion, consider abnormal or disproportionate;
          </li>
          <li>
            access, scrape or use the Service in a way that violates the
            Agreement or any published rate limit, quota or technical
            restriction;
          </li>
          <li>
            misrepresent your identity, impersonate any person or organisation,
            or forge headers, IP addresses, packets or metadata; or
          </li>
          <li>
            use the Service to develop, train or evaluate a competing product or
            service, or to benchmark the Service for publication without our
            prior written consent.
          </li>
        </LegalList>
      </LegalSection>

      <LegalSection id="network" title="4. Network and traffic">
        <p>
          Our infrastructure is shared. We expect normal, well-behaved network
          use. The following are not permitted and can lead to throttling,
          suspension or termination at our sole discretion:
        </p>
        <LegalList>
          <li>
            sustained traffic that, in our judgement, materially impacts host or
            platform stability, the experience of other customers, or the
            operating economics of your plan;
          </li>
          <li>
            generating egress traffic specifically designed to consume host
            bandwidth (for example, running public file mirrors, torrent
            seedboxes or media-streaming relays at scale) without prior written
            approval;
          </li>
          <li>
            originating attack traffic toward third parties, regardless of
            whether your Cube was compromised by an attacker or by your own
            workload;
          </li>
          <li>
            traffic patterns that, in our judgement, are likely to attract
            denial-of-service, reputation-list or blocklist attention against
            our IP space.
          </li>
        </LegalList>
        <p>
          If your Cube is the target of an attack that threatens the stability
          of the host or our network, we may null-route the affected IP, change
          your IP, throttle traffic, sleep the Cube or take any other measure we
          consider necessary to protect our infrastructure and other customers.
          We are not liable for any interruption resulting from such measures.
        </p>
      </LegalSection>

      <LegalSection
        id="security"
        title="5. Security and vulnerability research"
      >
        <p>
          You may perform vulnerability testing on your own Cubes and your own
          systems running inside them. You must not test, probe, scan or attack
          any {PRODUCT_NAME} system, network, dashboard, API, control plane or
          any other customer&apos;s infrastructure without prior written
          permission from us. If you discover a security issue in our Service,
          please report it responsibly to{" "}
          <a
            className="text-primary hover:underline"
            href={`mailto:${PLATFORM_EMAILS.support}`}
          >
            {PLATFORM_EMAILS.support}
          </a>{" "}
          and give us a reasonable opportunity to investigate and remediate
          before disclosing it publicly.
        </p>
      </LegalSection>

      <LegalSection id="reporting" title="6. Reporting abuse">
        <p>
          If you believe {PRODUCT_NAME} is being used to violate this AUP,
          please send a report to{" "}
          <a
            className="text-primary hover:underline"
            href={`mailto:${PLATFORM_EMAILS.support}`}
          >
            {PLATFORM_EMAILS.support}
          </a>
          . Please include URLs, IP addresses, timestamps in UTC, and any
          evidence that helps us investigate quickly. We may, but are not
          obliged to, update you on the status or outcome of an investigation.
        </p>
      </LegalSection>

      <LegalSection id="enforcement" title="7. Enforcement">
        <p>
          We may investigate suspected violations and take any action we
          consider appropriate, in our sole discretion. When we identify a
          violation, we may try to contact you first so you have the opportunity
          to fix it, but we are not required to. In urgent or high-severity
          cases — for example, attacks in progress, CSAM, legal orders, security
          incidents or risks to our infrastructure — we may immediately and
          without notice:
        </p>
        <LegalList>
          <li>sleep, sandbox, throttle or remove affected Cubes;</li>
          <li>
            null-route IPs, revoke custom-domain routing or disable API access;
          </li>
          <li>
            suspend or terminate the offending account and any related accounts;
          </li>
          <li>
            preserve, copy, disclose or hand over data as we determine is
            appropriate to comply with applicable law, a valid legal request or
            to protect our or others&apos; rights, property or safety;
          </li>
          <li>
            forfeit any unused credit, top-ups and prepaid subscription fees and
            apply them to damages, mitigation costs, investigation costs,
            chargeback fees and other amounts caused by the violation; and
          </li>
          <li>
            pursue any other remedy available to us at law or in equity,
            including injunctive relief and recovery of legal costs.
          </li>
        </LegalList>
        <p>
          Repeat, severe or egregious violations will result in permanent
          account termination and may be referred to law enforcement.
        </p>
      </LegalSection>

      <LegalSection id="changes" title="8. Changes to this AUP">
        <p>
          We may update this AUP at any time as the Service evolves and as we
          learn about new forms of abuse. The updated AUP takes effect when
          posted unless we specify a later effective date. Your continued use of
          the Service after the effective date constitutes acceptance of the
          updated AUP.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
