/**
 * Build all Krova VM images locally (Docker), zstd-compress rootfs files,
 * compute sha256, and register/upsert a row in `platform_images`.
 *
 * NO upload step. Files stay on the Dokploy host's filesystem at
 * `KROVA_BUILD_OUTDIR` (a path that's bind-mounted host↔worker container at
 * the same location). The server-pull-images setup phase reads them from
 * there and SFTPs the bytes to bare-metal servers as part of provisioning.
 *
 * Designed to run inside the Dokploy worker container with:
 *   - /var/run/docker.sock mounted (lets in-container CLI talk to host daemon)
 *   - /opt/krova-build:/opt/krova-build bind mount (same path on both sides
 *     so docker run -v works correctly under Docker-out-of-Docker)
 *   - KROVA_BUILD_OUTDIR=/opt/krova-build/images
 */

import { spawnSync } from "child_process";
import { createHash } from "crypto";
import { and, eq, inArray, ne } from "drizzle-orm";
import {
  closeSync,
  createReadStream,
  existsSync,
  openSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from "fs";
import { tmpdir } from "os";
import { basename, dirname, join, resolve } from "path";
import { fileURLToPath } from "url";

import {
  CUBE_IMAGES,
  FIRECRACKER_VERSION,
  KERNEL_CONFIG_VERSION,
  KERNEL_VERSION,
} from "@/config/platform";
import { formatImageVersion } from "@/lib/version";

if (existsSync(".env")) {
  process.loadEnvFile();
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
/**
 * IMAGES_DIR must match the OUTDIR that build-all-images.sh writes to. The
 * bash script computes its default as `$SCRIPT_DIR/images`, so when the
 * script lives at `setup/images/build-all-images.sh`, the default OUTDIR is
 * `setup/images/images` (a subdirectory next to the script).
 *
 * Override via `KROVA_BUILD_OUTDIR` — required when running inside a
 * container that talks to the host docker daemon: the path must exist on
 * BOTH the host and the container at the same location so docker run's
 * `-v` bind mounts resolve correctly on both sides.
 */
const IMAGES_DIR =
  process.env.KROVA_BUILD_OUTDIR || resolve(REPO_ROOT, "setup/images/images");
const LOCK_FILE = "/tmp/krova-image-build.lock";

interface ImageSpec {
  /** Whether to compress with zstd before registering. */
  compress: boolean;
  /** Final on-disk filename (under IMAGES_DIR) recorded in platform_images. */
  finalFilename: string;
  kind: "kernel" | "rootfs";
  /** Local source path produced by build-all-images.sh. */
  localPath: string;
  name: string;
}

// Single source of truth: `CUBE_IMAGES` from config/platform.ts. The IMAGES
// list below is mechanically derived — kernel always first, then one rootfs
// entry per CUBE_IMAGES entry. To add/remove a distro, edit CUBE_IMAGES.
const IMAGES: ImageSpec[] = [
  {
    name: "kernel",
    kind: "kernel",
    localPath: `${IMAGES_DIR}/kernel/vmlinux`,
    compress: false,
    finalFilename: "vmlinux",
  },
  ...CUBE_IMAGES.map(
    (img): ImageSpec => ({
      name: img.id,
      kind: "rootfs",
      localPath: `${IMAGES_DIR}/${img.id}/rootfs.ext4`,
      compress: true,
      finalFilename: `${img.id}.ext4.zst`,
    })
  ),
];

/**
 * Write a generated bash snippet describing every distro to a temp file,
 * then point the build script at it via env var. The bash script sources
 * this file and dispatches generically — no hardcoded `do_<name>`
 * functions or per-distro case branches.
 *
 * Format is plain `KEY=VALUE` bash assignments + a `KROVA_DISTROS` array
 * of IDs. Each ID maps to four indexed parallel arrays for
 * (family|vendor|version|codename|dockerImage) lookup. Bash arrays + a
 * loop are easier to debug than jq + JSON inside a script that already
 * has its share of quoting traps (see CLAUDE.md rule 39).
 *
 * Returns the temp file path so the caller can clean it up.
 */
function writeDistrosSnippet(): string {
  const lines: string[] = [
    "# Auto-generated by scripts/build-images.ts. Do not edit by hand.",
    "# Sourced by setup/images/build-all-images.sh via $KROVA_DISTROS_FILE.",
    "",
    `KROVA_DISTRO_IDS=(${CUBE_IMAGES.map((i) => `"${i.id}"`).join(" ")})`,
    `KROVA_DISTRO_FAMILIES=(${CUBE_IMAGES.map((i) => `"${i.family}"`).join(" ")})`,
    `KROVA_DISTRO_VENDORS=(${CUBE_IMAGES.map((i) => `"${i.vendor}"`).join(" ")})`,
    `KROVA_DISTRO_VERSIONS=(${CUBE_IMAGES.map((i) => `"${i.version}"`).join(" ")})`,
    `KROVA_DISTRO_CODENAMES=(${CUBE_IMAGES.map((i) => `"${i.codename}"`).join(" ")})`,
    `KROVA_DISTRO_DOCKER_IMAGES=(${CUBE_IMAGES.map((i) => `"${i.dockerImage}"`).join(" ")})`,
    // "1" = preinstall Docker Engine + Compose into the rootfs, "0" = leave bare.
    // Bash has no native bool — "1"/"0" strings are the path of least surprise.
    `KROVA_DISTRO_PREINSTALL_DOCKER=(${CUBE_IMAGES.map((i) => `"${i.preinstallDocker ? "1" : "0"}"`).join(" ")})`,
    "",
  ];
  const path = join(tmpdir(), `krova-distros-${process.pid}.sh`);
  writeFileSync(path, lines.join("\n"), { mode: 0o600 });
  return path;
}

let lockFd: number | null = null;

function acquireLock() {
  if (existsSync(LOCK_FILE)) {
    console.error(
      `Another build is in progress (lock file ${LOCK_FILE} exists). Exiting.`
    );
    process.exit(1);
  }
  lockFd = openSync(LOCK_FILE, "wx");
}

function releaseLock() {
  if (lockFd != null) {
    try {
      closeSync(lockFd);
    } catch {
      /* noop */
    }
    lockFd = null;
  }
  try {
    if (existsSync(LOCK_FILE)) {
      unlinkSync(LOCK_FILE);
    }
  } catch {
    /* noop */
  }
}

function preflightDocker() {
  const result = spawnSync("docker", ["info"], { stdio: "pipe" });
  if (result.status !== 0) {
    throw new Error(
      "Docker is not reachable. If running inside a container (Dokploy), " +
        "ensure /var/run/docker.sock is mounted into the container. " +
        `Underlying error: ${(result.stderr?.toString() || result.error?.message || "unknown").slice(0, 300)}`
    );
  }
}

function runBuild() {
  console.log("→ Preflight: checking Docker availability ...");
  preflightDocker();
  console.log(
    `→ Building ${CUBE_IMAGES.length} rootfs distro(s) + kernel via setup/images/build-all-images.sh (Firecracker ${FIRECRACKER_VERSION}) ...`
  );
  console.log(
    `  Distros (from config/platform.ts CUBE_IMAGES): ${CUBE_IMAGES.map((i) => i.id).join(", ")}`
  );
  // Generate a bash snippet describing every distro, then point the build
  // script at it via env var. The build script sources this file and
  // dispatches generically — adding/removing a distro only requires editing
  // CUBE_IMAGES in config/platform.ts; no bash edits needed.
  const distrosFile = writeDistrosSnippet();
  try {
    const result = spawnSync("bash", ["setup/images/build-all-images.sh"], {
      cwd: REPO_ROOT,
      stdio: "inherit",
      env: {
        ...process.env,
        FC_VERSION: FIRECRACKER_VERSION,
        KVER: KERNEL_VERSION,
        CONFIG_KVER: KERNEL_CONFIG_VERSION,
        KROVA_DISTROS_FILE: distrosFile,
      },
    });
    if (result.status !== 0) {
      throw new Error(`build-all-images.sh exited with code ${result.status}`);
    }
  } finally {
    try {
      unlinkSync(distrosFile);
    } catch {
      /* noop */
    }
  }
}

function assertExpectedBuildArtifacts(): void {
  const missing = IMAGES.filter((spec) => !existsSync(spec.localPath));
  if (missing.length === 0) {
    return;
  }

  const detail = missing
    .map((m) => `- ${m.name}: expected ${m.localPath}`)
    .join("\n");
  throw new Error(
    `Build completed but some required artifacts are missing:\n${detail}\n` +
      "Refusing to register partial image set."
  );
}

function compressFile(input: string, output: string): void {
  console.log(`→ Compressing ${basename(input)} → ${basename(output)} ...`);
  // -1 = fastest, -T0 = use all cores (matches snapshot compression in cube-snapshot).
  // -f = overwrite existing output, --rm removed (we keep input until success).
  const result = spawnSync("zstd", ["-1", "-T0", "-f", input, "-o", output], {
    stdio: "inherit",
  });
  if (result.status !== 0) {
    throw new Error(`zstd compression failed for ${input}`);
  }
}

function sha256OfFile(path: string): Promise<string> {
  return new Promise((resolveHash, rejectHash) => {
    const hash = createHash("sha256");
    const stream = createReadStream(path);
    stream.on("data", (chunk) => hash.update(chunk));
    stream.on("end", () => resolveHash(hash.digest("hex")));
    stream.on("error", rejectHash);
  });
}

async function main() {
  acquireLock();
  process.on("exit", releaseLock);
  process.on("SIGINT", () => {
    releaseLock();
    process.exit(130);
  });
  process.on("SIGTERM", () => {
    releaseLock();
    process.exit(143);
  });

  try {
    runBuild();
    assertExpectedBuildArtifacts();

    const [{ db }, { platformImages }, { cubes }] = await Promise.all([
      import("@/lib/db"),
      import("@/db/schema/platform-images"),
      import("@/db/schema/cubes"),
    ]);

    for (const spec of IMAGES) {
      if (!existsSync(spec.localPath)) {
        throw new Error(
          `Required build artifact missing for ${spec.name}: ${spec.localPath}`
        );
      }

      const finalPath = `${IMAGES_DIR}/${spec.finalFilename}`;

      if (spec.compress) {
        compressFile(spec.localPath, finalPath);
        // Remove the uncompressed source — we keep only the compressed final.
        try {
          unlinkSync(spec.localPath);
        } catch {
          /* noop — best-effort */
        }
      } else if (spec.localPath !== finalPath) {
        // Move the uncompressed artifact to its final filename if the build
        // wrote it under a different name (e.g. kernel/vmlinux → vmlinux).
        const mv = spawnSync("mv", [spec.localPath, finalPath]);
        if (mv.status !== 0) {
          throw new Error(`Failed to move ${spec.localPath} → ${finalPath}`);
        }
      }

      const sizeBytes = statSync(finalPath).size;
      const sha = await sha256OfFile(finalPath);

      console.log(
        `→ Registered ${spec.name} (${(sizeBytes / 1024 / 1024).toFixed(1)} MB, sha256:${sha.slice(0, 12)}…) at ${finalPath}`
      );

      // Version bump rule: increment `version` (the minor) when the artifact's
      // sha256 changes (i.e. content actually changed — kernel rebuilt with
      // new options, rootfs got security patches). Idempotent rebuilds that
      // produce identical bytes do NOT bump version. Cubes track which
      // version they cold-booted with via `cubes.bootedKernelVersion` /
      // `cubes.provisionedRootfsVersion` so the UI can flag "you're behind
      // the latest, restart to upgrade".
      //
      // Display scheme is `${IMAGE_VERSION_MAJOR}.${minor}` — first build of
      // a fresh artifact starts at minor=0 (= v1.0), each sha change
      // increments the minor (v1.1, v1.2, …, v1.10, v1.11).
      const existing = await db.query.platformImages.findFirst({
        where: eq(platformImages.name, spec.name),
        columns: { sha256: true, version: true },
      });
      const nextVersion =
        existing == null
          ? 0
          : existing.sha256 === sha
            ? existing.version
            : existing.version + 1;
      const versionChanged =
        existing != null && nextVersion !== existing.version;

      await db
        .insert(platformImages)
        .values({
          name: spec.name,
          kind: spec.kind,
          path: finalPath,
          sizeBytes,
          sha256: sha,
          version: nextVersion,
        })
        .onConflictDoUpdate({
          target: platformImages.name,
          set: {
            kind: spec.kind,
            path: finalPath,
            sizeBytes,
            sha256: sha,
            version: nextVersion,
            updatedAt: new Date(),
          },
        });

      if (versionChanged) {
        console.log(
          `  ↑ Version bumped: v${formatImageVersion(existing!.version)} → v${formatImageVersion(nextVersion)} (sha256 changed)`
        );
      } else if (existing == null) {
        console.log(`  ◆ First version: v${formatImageVersion(nextVersion)}`);
      } else {
        console.log(
          `  = Version unchanged: v${formatImageVersion(nextVersion)} (sha256 match)`
        );
      }
    }

    // ── Auto-prune orphaned platform_images rows ──────────────────────────
    //
    // Single-source-of-truth enforcement: anything in `platform_images`
    // whose name is NOT in `CUBE_IMAGES` (or the special "kernel" row) is
    // an orphan from a previously-supported distro that has since been
    // removed from `config/platform.ts`. Sweep them out so the DB stays in
    // sync with the source-of-truth.
    //
    // Safety net: if any non-deleted cube still references an orphaned
    // image (cubes.imageId), refuse to prune — log a loud warning instead.
    // The operator can then either resurrect the distro in CUBE_IMAGES,
    // explicitly purge the dependent cubes, or manually delete the row
    // after migrating the cubes off it.
    const knownNames = new Set(["kernel", ...CUBE_IMAGES.map((i) => i.id)]);
    const allRows = await db
      .select({
        id: platformImages.id,
        name: platformImages.name,
        path: platformImages.path,
      })
      .from(platformImages);
    const orphans = allRows.filter((r) => !knownNames.has(r.name));

    if (orphans.length > 0) {
      const orphanNames = orphans.map((o) => o.name);
      const referencingCubes = await db
        .select({ id: cubes.id, name: cubes.name, imageId: cubes.imageId })
        .from(cubes)
        .where(
          and(ne(cubes.status, "deleted"), inArray(cubes.imageId, orphanNames))
        );

      if (referencingCubes.length > 0) {
        console.warn("");
        console.warn(
          `⚠ Refusing to prune ${orphans.length} orphaned platform_images row(s) — ${referencingCubes.length} active cube(s) still reference them:`
        );
        for (const c of referencingCubes) {
          console.warn(`    cube "${c.name}" (${c.id}) → image "${c.imageId}"`);
        }
        console.warn(
          "  Resolution: either re-add the missing distro(s) to CUBE_IMAGES in config/platform.ts, " +
            "or delete/migrate the listed cubes, then re-run pnpm build:images."
        );
        console.warn(`  Orphans being kept for now: ${orphanNames.join(", ")}`);
      } else {
        // Safe to prune. Remove the on-disk artifacts first, then drop
        // the DB rows. Disk cleanup is best-effort — if a file is gone
        // already, that's fine.
        for (const orphan of orphans) {
          if (orphan.path) {
            try {
              if (existsSync(orphan.path)) {
                unlinkSync(orphan.path);
                console.log(`  Removed stale build artifact: ${orphan.path}`);
              }
            } catch (err) {
              console.warn(
                `  Failed to remove ${orphan.path} (will still drop DB row):`,
                err instanceof Error ? err.message : err
              );
            }
          }
        }
        await db.delete(platformImages).where(
          inArray(
            platformImages.id,
            orphans.map((o) => o.id)
          )
        );
        console.log(
          `✓ Pruned ${orphans.length} orphaned platform_images row(s) (no longer in CUBE_IMAGES, no active cubes referencing): ${orphanNames.join(", ")}`
        );
      }
    }

    console.log("✓ Done — all images built and registered.");
    process.exit(0);
  } catch (err) {
    console.error("✗ Build failed:", err);
    releaseLock();
    process.exit(1);
  }
}

main();
